let name = "Matvii";
let surname = "Stoliaruk";
let group = "Lv-476.JS Core";
let yearOfBirth = 1996;
let isMarried;
isMarried = false;
console.log(typeof name);
console.log(typeof surname);
console.log(typeof group);
console.log(typeof yearOfBirth);
console.log(typeof isMarried);
console.log(yearOfBirth);
console.log(isMarried);
console.log(name);
console.log(surname);
console.log(group);
let x = null;
let y;
console.log(typeof x);
console.log(typeof y);